# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0002_remove_webdes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='webdes',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AddField(
            model_name='webdes',
            name='categories',
            field=models.ManyToManyField(related_name='webdes', to='webdes.Category'),
        ),
    ]
