# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-20 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0004_auto_20191120_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
