# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdes',
            name='category',
        ),
    ]
