# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0006_auto_20191127_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdes',
            name='categories',
        ),
        migrations.AddField(
            model_name='webdes',
            name='category',
            field=models.CharField(choices=[('P', 'Professional'), ('E', 'Events'), ('A', 'Abstract'), ('N', 'Non-profit')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
