# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0008_auto_20191201_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
