# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0009_auto_20191201_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdes',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='webdes.Category'),
        ),
    ]
