# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdes', '0011_auto_20191201_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdes',
            name='categories',
        ),
        migrations.AddField(
            model_name='webdes',
            name='category',
            field=models.CharField(choices=[('P', 'Professional'), ('E', 'Event'), ('A', 'Abastract'), ('NP', 'Non-Profit')], default='Event', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
